config/routes.rb
Storeconf2::Application.routes.draw do
  resources :hosts
  resources :resources
  root :to => 'hosts#index'

end

app/models/fact_name.rb
class FactName < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/fact_value.rb
class FactValue < ActiveRecord::Base
  belongs_to :host
  belongs_to :fact_name

  def name
    fact_name
  end
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many :resources
  has_many :facts, :class_name => FactValue
end

app/models/param_name.rb
class ParamName < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/param_value.rb
class ParamValue < ActiveRecord::Base
  belongs_to :resource
  belongs_to :param_name

  def name
    param_name
  end
end

app/models/puppet_tag.rb
class PuppetTag < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :host
  belongs_to :source_file
  has_many :parameters, :class_name => ParamValue
  has_many :resource_tags
  has_many :puppet_tags, :through => :resource_tags

  def tags
    puppet_tags
  end

  def file
    source_file
  end
end

app/models/resource_tag.rb
class ResourceTag < ActiveRecord::Base
  belongs_to :resource
  belongs_to :puppet_tag
end

app/models/source_file.rb
class SourceFile < ActiveRecord::Base
  has_many :resources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
    @hosts = Host.all
  end

  def show
    @host = Host.find(params[:id])
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hosts/index.html.erb
<h1>Hosts</h1>
<table class="table">
  <tr>
    <th>Name</th>
  </tr>
  <% @hosts.each do |host| %>
    <tr>
      <td><%= link_to host.name, host_path(host) %></td>
    </tr>
  <% end %>
</table>

app/views/hosts/show.html.erb
<h1><%= @host.name %></h1>
<p>
  <%= link_to "Back", hosts_path, :class => "btn" %>
</p>

<h2>Exported Resources</h2>
<table class="table">
  <tr>
    <td>Type</td>
    <td>Title</td>
    <td>Tags</td>
    <td>Parameters</td>
    <td></td>
  </tr>
  <% @host.resources.where(:exported => true).each do |resource| %>
    <tr>
      <td><%= resource.restype %></td>
      <td><%= resource.title %></td>
      <td><%= resource.tags.collect {|t|t.to_s}.join(", ") %></td>
      <td>
        <% resource.parameters.each do |param| %>
          <%= param.name %>=<%= param.value %><br>
        <% end %>
      </td>
      <td><%= link_to "Delete", resource_path(resource), :method => :delete %></td>
    </tr>
  <% end %>
</table>

<h2>Facts</h2>
<table class="table">
  <% @host.facts.each do |fact| %>
    <tr>
      <td><%= fact.name %></td>
      <td><%= fact.value %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storeconf2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Storeconf2</a>
    <ul class="nav">
      <li><%= link_to "Hosts", hosts_path %></li>
    </ul>
  </div>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>